# Generated by Django 3.0.5 on 2021-12-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindShopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopID', models.IntegerField()),
                ('shopName', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'findshopapp_product',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('Product', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=20)),
                ('shopName', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('cityMunicipality', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('contactNumber', models.IntegerField()),
            ],
            options={
                'db_table': 'findshopapp_shops',
            },
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
